### PR TITLE
Updated the CSS files to hopefully eradicate that pesky white border.

### PR DESCRIPTION
**Pull request by mickgingy**
Samit and Nick, let me know if it looks any better on PhoneGap

### CODE REVIEW

**Comment by sag131** [comment]
White border still there.

**Comment by sag131** [comment]
I suppose it doesn't need to be perfect.  She'll most likely redo most of
the html/css anyway.

**Comment by mickgingy** [comment]
Damn, that's frustrating. Could you email a screenshot? Or is it exactly the same as before?

**Comment by sag131** [comment]
Same

**Pull request closed without merging**
